(require 'less-mode)
(add-to-list 'auto-mode-alist '("\\.less$" . less-mode))
(defun semicolon-ret ()
  (interactive)
  (insert ";")
  (newline-and-indent)
  )
(defun brace-ret-brace ()
  (interactive)
  (insert "{") (newline-and-indent)
  (newline-and-indent)
  (insert "}") (indent-for-tab-command)
  (newline-and-indent) (newline-and-indent)
  (previous-line) (previous-line) (previous-line)
  (indent-for-tab-command)
  )
(add-hook 'css-mode-hook
              (lambda ()
                (setq css-indent-offset 2)
                (define-key css-mode-map ";" 'semicolon-ret)
                (define-key css-mode-map "{" 'brace-ret-brace)
                ))
