;; js2-mode
(autoload 'js2-mode "js2-mode" nil t)
(add-to-list 'auto-mode-alist '(".js$" . js2-mode))
(add-to-list 'auto-mode-alist '(".mayaa$" . xml-mode))
(add-to-list 'auto-mode-alist '(".as$" . javascript-mode))
(setq js2-strict-missing-semi-warning t)
(add-hook 'js2-mode-hook
          '(lambda ()
             (local-set-key "\C-ci" 'js-doc-insert-function-doc)
             (local-set-key "\C-c@" 'js-doc-insert-tag)
             (local-set-key "\C-cf" 'js-doc-insert-file-doc)
             (setq js2-additional-externs '("jQuery"))
             (setq js2-additional-externs '("$"))
             (setq js2-additional-externs '("goog"))
             (setq js2-additional-externs '("ko"))
             (setq js2-additional-externs '("camp"))
             (setq javascript-indent-level 2
                   javascript-expr-indent-offset 2
                   indent-tabs-mode nil)
             )
          )

(setq js2-always-indent-assigned-expr-in-decls-p t)
(setq js2-auto-indent-p t)
(setq js2-basic-offset 2)
(setq js2-bounce-indent-p nil)
(setq js2-cleanup-whitespace t)
(setq js2-consistent-level-indent-inner-bracket-p t)
(setq js2-dynamic-idle-timer-adjust 2)
(setq js2-enter-indents-newline t)
(setq js2-global-externs t)
(setq js2-highlight-level 3)
(setq js2-idle-timer-delay 0)
(setq js2-indent-on-enter-key t)
(setq js2-missing-semi-one-line-override t)
(setq js2-rebind-eol-bol-keys nil)
(setq js2-skip-preprocessor-directives t)
(setq js2-strict-inconsistent-return-warning nil)
(setq js2-use-ast-for-indentation-p t)
