(let ((default-directory (expand-file-name "~/.emacs.d/elisps")))
  (add-to-list 'load-path default-directory)
  (if (fboundp 'normal-top-level-add-subdirs-to-load-path)
      (normal-top-level-add-subdirs-to-load-path)))


(require 'coffee-mode)
(require 'anything-startup)
(require 'anything-config)
(require 'auto-complete)
(require 'auto-install)
(require 'google-c-style)
(require 'js-doc)
(require 'textile-mode)
(require 'yasnippet)
(require 'init-loader)
(init-loader-load "~/.emacs.d/init/cmp")
(require 'moccur-edit)
